### ISSUE TITLE
MAC下出错

### ISSUE THREAD

**Issue by xswya** [Ryqsky/wechat-jump-game-js#1]
utils.js
const ADB_PATH = '/usr/local/bin/adb'; #已更改
运行
npm i --registry=https://registry.npm.taobao.org 
报错
npm WARN wechat-jump-game@1.0.0 No repository field.

**Comment by Ryqsky** [comment]
npm WARN wechat-jump-game@1.0.0 No repository field.

这个命令表示你正在安装wechat-jump-game这个包啊。

你在项目的根目录然后运行 npm install 安装依赖看看。

**Comment by xswya** [comment]
按了start没反应~

**Comment by Ryqsky** [comment]
看看你运行npm start 的CMD等bash命令窗口下，有没有错误日志，根据错误信息排查就可以。
一般情况是你手机没连上电脑。ADB命令没生效。

**Comment by xswya** [comment]
OK 解决了。images文件夹下少了一个jump_screencap文件夹，造成pull失败。

**Comment by Ryqsky** [comment]
嗯嗯嗯，那我加一行创建该目录的代码。
